name = "Spotifakt-Theme"
license = "MIT License" #original Codrops Lisense is here http://tympanus.net/codrops/licensing/
licenselink = "//github.com/uZer/spotifakt-theme/blob/master/LICENSE.md"
description = "Theme for Spotifakt"
homepage = "//github.com/uZer/spotifakt-theme"
tags = ["responsive", "grid", "portfolio", "cards", "simple", "collections", "google analytics"]
min_version = 0.15

[author]
  name = "Youenn Piolet"
  homepage = "//github.com/uZer/spotifakt-theme"

[original]
  name = "Hugrid (Hugo+grid) Thumbnail Grid with Expanding Preview (Pavel Kanyshev)"
  homepage = "//github.com/aerohub/hugrid"
  repo = "//github.com/aerohub/hugrid"
